
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


</head>







  <div class="flex-container">
    <div class="zoom">  <div><img src='<?php echo $this->getViewFileUrl('Ceymox_Training::images/img.jpg'); ?>'  width="170" height="180"/></div></div>
          <div class="zoom"><div><img src='<?php echo $this->getViewFileUrl('Ceymox_Training::images/2.jpeg'); ?>'  width="170" height="180"/></div></div>
     <div class="zoom"><div><img src='<?php echo $this->getViewFileUrl('Ceymox_Training::images/2.jpeg'); ?>'  width="170" height="180"/></div></div>
      <div class="zoom"><div><img src='<?php echo $this->getViewFileUrl('Ceymox_Training::images/images.jpeg'); ?>'  width="170" height="180"/></div></div>
       <a href="index"><button type="button" class="btn btn-info btn-lg">Back</button></a>
    </div>



