
  	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>




<div class="p">
<div class="container">
        <div class="row centered-form"><a href="index"><button type="button" class="btn btn-info btn-lg" style="margin-left:1100px;">Back</button></a>
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Please sign In  <small></small></h3>
			 			</div>
			 			<div class="panel-body">
			    	
			    			<div class="form-group">
			    				<input type="email" name="emails" id="emails" class="form-control input-sm" placeholder="Email Address">
			    			</div>

			    			<div class="form-group">
			    				<input type="password" name="pass" id="pass" class="form-control input-sm" placeholder="Password">
			    			</div>

			    			
			    			<input type="submit" value="Login" class="btn btn-info btn-block">
			    		
			    		</form>

			    	</div>
	    		</div><br><br><br>
    		</div>
    	</div>
    </div></div>
