<!--span style="font-weight: 400;">Hello World</span-->

<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<div class="p">
<center>
<marquee direction="left"><font  color="white"><strong><h3><?php
echo $block->helloWorld();?></h3></strong></font></center></marquee>
<br>
<h5><font color="red" style="margin-left:1080px;"><a href="signup"><font color="red">Sign Up</font></a>&nbsp&nbsp&nbsp<a href="signin"><font color="white">Sign In</font></a></font></h5>
<div class="zoom">
<img src='<?php echo $this->getViewFileUrl('Ceymox_Training::images/img.jpg'); ?>'  width="170" height="180"/></div><br >

<center>
<font color="red"><strong><?php
echo "Today is " . date("Y/m/d") . "<br>";?></strong></font><br>


<div class="container">
  <h2>Ceymox Technologies</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">More Info</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Welcome</h4>
        </div>
        <div class="modal-body">
          <p>The Digital Technologists for your Online Business
Transform your eCommerce Engine with Magento’s Magic</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
</center></center><br></div>
  <div class="flex-container">
      <div><center><a href="home">HOME</a></div>
      <div><center><a href="about">ABOUT US</a></div>
      <div><center><a href="gallery">GALLERY</a></div>
      <div><center><a href="contact">CONTACT US</a></div>
    </div>
</center>


